### ISSUE TITLE
Raspberry pi 3 bluetooth

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#796]

**Comment by paradadf** [comment]
The commit from  April 3rd [here](https://github.com/libretro/Lakka/commits/lakka) has a fix for bluetooth that might be useful. The commit itself can be found [here](https://github.com/libretro/Lakka/commit/25646a66629899b21307c3e6e8a357c5ee7f9200).

Among the patches, there was an initial [commit](https://github.com/libretro/Lakka/commit/746bdb18569bb6a1bf129469caf5571440041be7) on March 14th adding patched for Shanwan/Gasia support. The patches were updated together with bluez in the commit from April 3rd. Maybe those patches work as an unified driver for ps3 controlleres (+clones) as intended in https://github.com/recalbox/recalbox-os/issues/615

**Comment by disappear89** [comment]
Does also a extra bluetooth dongle doesn`t work on the PI 3? I bought one and tried to use it on my PI 3 but also no luck =(

**Comment by disappear89** [comment]
I got it running now with an extra USB dongle. But it only works if i restart the bluetooth service again manually.
As workaround you can SSH to the box and do the following:
mount -o remount,rw /
vi /etc/init.d/S99custom
Append:
-----
/etc/init.d/S32bluetooth restart
-----
Reboot..

**Comment by bigboo3000** [comment]
you can find here what they did in Lakka to support it
https://github.com/libretro/Lakka/issues/314

**Comment by drcrimzon** [comment]
I almost have this fixed.  I have the module up and running, and I can see and pair bluetooth devices.  I have an issue with the bluetooth script right now that is preventing them from staying connected, should have that fixed today.  Once I make sure all is well with a fresh install will send over my changes.

**Comment by drcrimzon** [comment]
[bluetooth]# exit 
[DEL] Controller B8:27:EB:19:7B:CD BlueZ 5.37 [default] 
# hciconfig hci0 up 
# bluetoothctl 
[NEW] Controller B8:27:EB:19:7B:CD BlueZ 5.37 [default] 
[bluetooth]# scan on 
Discovery started 
[CHG] Controller B8:27:EB:19:7B:CD Discovering: yes 
[NEW] Device 54:60:09:1D:85:6E 54-60-09-1D-85-6E 
[NEW] Device 01:03:9F:74:71:1F 01-03-9F-74-71-1F
[CHG] Device 01:03:9F:74:71:1F LegacyPairing: no 
[CHG] Device 01:03:9F:74:71:1F Name: 8Bitdo NES30 Pro 
[CHG] Device 01:03:9F:74:71:1F Alias: 8Bitdo NES30 Pro 
[bluetooth]# 
[bluetooth]# pair 01:03:9F:74:71:1F 
Attempting to pair with 01:03:9F:74:71:1F 
[CHG] Device 01:03:9F:74:71:1F Connected: yes 
[CHG] Device 01:03:9F:74:71:1F Modalias: usb:v3820p0009d0100 
[CHG] Device 01:03:9F:74:71:1F UUIDs: 00001124-0000-1000-8000-00805f9b34fb 
[CHG] Device 01:03:9F:74:71:1F UUIDs: 00001200-0000-1000-8000-00805f9b34fb 
[CHG] Device 01:03:9F:74:71:1F Paired: yes 
Pairing successful 
[CHG] Device 01:03:9F:74:71:1F Connected: no 
[bluetooth]# trust 01:03:9F:74:71:1F 
[CHG] Device 01:03:9F:74:71:1F Trusted: yes 
Changing 01:03:9F:74:71:1F trust succeeded

**Comment by drcrimzon** [comment]
https://github.com/drcrimzon/recalbox-buildroot/commit/69c4be533308ba6b8f5b0f5d243c4e34f19eb54e

fixed and working...  I had to change the bluetooth script, there is no -u flag on bluez5, so I just run bluetoothd as a background task.  Also, it would not auto load the firmware and enable the device, so that the script checks if it is a rpi3 if the dtb is in /boot and if so enables the onboard bt.

So far, I have NOT tested it on a pi1/2 (I dont have any usb bt dongles around), but it works on my 3.  BT comes up, and I can pair / use devices without issue from gui and cli.

Once I test some more I'll create a pull request.  This is for anyone else out there to comment / test if they feel like it.

**Comment by substring** [comment]
Hey @drcrimzon
I've been working on pi3 bt on my side too. Haven't committed upstream yet because the thing is a little more difficult than just adding bluez5 :
- the hidd command doesn't exist anymore, so `bluetoothcontrollers.sh` has to be totally reworked.
- as bluez5 has native support for official sixaxis, i'm also working on having clones working too. Shanwans are ok, not GAsia
- as you noticed, known devices are stored in `/var/lib/bluetooth` which is not a persistant file system. I partially solved it by tar-ing all, restoring it on reboot

Here is where i'm stuck :
- looks like `/etc/init.d/rcK` is never called when you turn off your system, so i can't save `/var/lib/bluetooth` on shutdown through an init script, which is sooooo bad
- my pi3 goes to kernel panic if i ever started a bt device. That's a known bug at the rpi foundation, i could solve it by running `hciconfig hci0 down` at shutdown but once again, init script problem

Don't forget we have to get rid off bluez4 (and eventually sixad/qtsixa because they 'll conflict with bluez5), so depending on it's an upgrade or a fresh install (commit on rb-4.1.X), you have to remove bluez4 binaries

**Comment by substring** [comment]
Ine last thing : you can't mke a symlink of `/var/lib/bluetooth` on your share, FAT32 filesystem doesn't like colons in filenames 😉

**Comment by drcrimzon** [comment]
Hey @substring, I've had a friend testing, since I've been too busy at work.  I have had a friend testing.  I just found out about the re-pair device every reboot, and havent had a chance to look at that.
hidd: Already working a revamp of S32bluetooth and bluetoothcontrollers.sh.  I didn't like the hackyness of my firmware load.
sixaxis: I only have official controllers, so I won't be much help testing here
/var/lib/bt: Can we link /var/lib/bluetooth to /recalbox/share/bluetooth? (It's ext4 on my box)

I have only been doing fresh installs, so bluez4 is gone.  Still need to work on sixad/qtsixa.

**Comment by substring** [comment]
hey @drcrimzon 
The only thing i can't test (yet) is pairing devices through ES. Haven't found out yet how to pair "regular" (understand non sixaxis) devices. Seems you can use bluetoothctl with heredoc or pipe an echo of bluetoothctl commands to the binary itself, but you said you solved it, i'm really glad about that :) Just remember the hard point is to save known devices to restore them on next boot, see the next point

`/var/lib/bluetooth` no you can't symlink, because quite many people are using a FAT32 key as their `/recalbox/share`. As i told you, for now I'm got restoring bt devices with a tarball, There might me some "nicer" ways to do it. I find a tarball so much easier to manage ... For now there is a problem about recalbox internals : don't expect to save anything on a `S32bluetooth stop` for now, I may fix it, it

Concerning bluez5, i took the 4 patchs from Phil Elwell, you could do the same (as he patched bluez to load firmwares from /var/lib, which is a little nicer than symlinking)
Last word about sixaxis : I didn't make many tests, but there may be a conflict between sixad/qtsixa and bluez5
If you wish , i may commit my changes to my repo if you want to compare

Oh and I forgot, from my previous messages : thank you for your interest and contribution to recalbox :)

**Comment by drcrimzon** [comment]
I would love to compare.  Thats why I posted this, hoping someone else was working on it and we could collaborate.

Since I dont have a bluetooth usb, where were devices saved before on bluez4?

Worst case, we could create a 50MB file in recalbox/share, i.e. bluetooth.fs, format it ext4, and mount that to var/lib/bluetooth.  Trying to think of ways to avoid having to run a backup at shutdown and restore at boot.

As far as bluetoothcontrollers, this should replace hidd fine:         

[ "$skip" == "1" ] && continue                                                                                                            echo -e 'connect $bt' | bluetoothctl 2>/dev/null &                                                                                        
waitForMe="$waitForMe $!"

**Comment by substring** [comment]
@digitallumberjack how are bt devices saved for now ? I remember it's something linked to "knowndevices" but like drcrimzon i have no bt dongle

For backup/save, maybe everytime you connect a bt device, add it to a file ? So that no need to save on exit, just restore on startup.

I'll commit my changes later today

**Comment by drcrimzon** [comment]
@substring I made the change to ES hiddpair function, but I lost it moving these branches around.  Let me find where I changed it again, and commit bluetoothcontroller.sh with it.

After changing all of this, we are committing to replacing bluez4 with 5 across all platforms.  I haven't looked at the upgrade process as you mentioned earlier.  I thought the upgrade was overwrite rootfs, and keep /recalbox/share, so that should get rid of and old blue4 references.

**Comment by drcrimzon** [comment]
@substring 
https://github.com/drcrimzon/recalbox-buildroot/commit/9986200faa1a1a57a5b45397437eaefc2fdfd49b

Here is the fix for recalbox-settings.sh to fix pair from menu.  this also has auto connect fixed.

I also changed S32bluetooth around to act more daemon like.  I broke the script and bluetoothd out so when you restart it actually restarts the script (before if you restart it would leave the old script running).
I'm at work, and can't test any of this yet.

If we can add in the patches you have to point to /lib/firmware and remove the link, we should be pretty close once we get the known_devices working properly.

**Comment by drcrimzon** [comment]
@substring 
After looking at the config and populate code, it looks like the files are backed up on connect (from gui at least) to the /recalbox/share/system/bluetooth folder, renaming the files in the process.  On boot, S12populate copies them back, putting the : back in.

So, this should be fixed as long as you pair from ES, which you should be able to do once you add my hidd replacements.

So the only issues left are the kernel panics?  I have not been able to reproduce that yet.
And checking the upgrade process out.

Anything I'm missing?

**Comment by substring** [comment]
@drcrimzon as i just have dual shock 3 clones, i applied some unofficial patches (dunno why they hve never been merged to bluez). The kernel panic happens on shutdown if a pad is paired. For an unknown reason it started to crash on shutdown with no reason, dunno why. It's ok when i run a `hciconfig hci0 down`. I haven't investigted much on that, but as i told you, it's a known bug

A few side notes :
- i'd say we shouldn't enable onboard bt if a dongle is connected
- still need to check if there are conflicts between sixad/qtsixa and bluez5
- i made a udev rule for instead of `hciconfig hci0 up pscan`
- should find a way to enable bt without locking the system as the firmware upload takes about 3 seconds or so. Maybe sthg like `(hciattach && hciconfig) &` could work, dunno

**Comment by substring** [comment]
need @digitalLumberjack to know what to do with sixad/qtsixa once upgraded to bluez5. Digi, do you agree to potentially loose GAsia compatibility for now but have a unified driver for DS3 ?

@drcrimzon you made a good job daemonizing bluetoothd, that was in my scope. 
for the known_devices stuff, seems like here on my pi3, the path is rather `/var/lib/bluetooth/PI3BTMAC/...`. I don't know if it's linked to me only testing DS3, but i'd be happy you confirm it and tell me how it happens when you pair your DS3, and other bt devices.

I'm now preparing the branch you shoulk look into for patches, and how far i made it

**Comment by substring** [comment]
https://github.com/recalbox/recalbox-buildroot/compare/rb-4.1.X...substring:rb-4.1.X-bluez5
I guess we have it all here. Just missing a clean way to run hciattach to start the pi3 bt

**Comment by drcrimzon** [comment]
I'll check out the extra folder tonight.

The scan / attach is not working right, it worked in my prior testing because I ran the scan manually first.  I'm having to get some work around to get bluetoothctl to run a scan so we can attach devices (Can't attach until bluetoothctl see's it).  I should have this working today, and will merge everything together, and see what pieces we are still missing.  

Currently I'm concerned about sixaxis pairing, since the udev script should not be working with bluez5, or it's not needed if it's working for you (It should not run because bluetoothd does not have a udev / u flag on bluez5).

And not enabling if a usb dongle is installed.  I've checked for all hidd instances, and switched them out, so the switch to bluez5 is almost complete.  Just need to fix the scan required before pairing issue.

**Comment by substring** [comment]
i'll order a 8bitdo next week for testing. For now it's weekend, time to enjoy free time ;)

**Comment by drcrimzon** [comment]
heck yeah. My friend is testing with his 8bitdo's, he loves them, so I might end up ordering some as well.
Have a great weekend!

**Comment by drcrimzon** [comment]
I can't get bluetoothctl to work right with STDIN...  Going to move to try a python bluez API which should work.  If it does, it will be a complete bluetooth management re-write.  I'm trying to avoid a bluetoothctl / stdin/stdbuf hack since it has never been reliable in my experience.

**Comment by nadenislamarre** [comment]
bluez 5 is much better for that as far as i have tested when i wanted to replace that too. the main primoblems is about joystock somupported in 4but not in bluez 5

**Comment by nadenislamarre** [comment]
bluez5 is really much better for that point. the point is tobmake joystick working in 4 working in 5 too which is not alwaysvthe case

**Comment by drcrimzon** [comment]
Yeah, thats one of the issues we have identified.  We know one of the sixaxis clone controllers will not work.  I know the 3bitdo controllers are working.  I guess once I can get the discovery/pairing/connecting switched to bluez5 we can test more.

I have tried to get the pi3 bluetooth to come up with bluez4 and I can't get it to bring the adapter up.  Everything I have found requires 5.27 for the pi3 adapter.

**Comment by substring** [comment]
@drcrimzon We can make the pi3 bt work with bluez4 quite easily : just compile bluez5 hciattach to load the driver, bluez4 will handle the rest like it used to until now

for bluetoothctl, my attempts with STDIN failed starting the agent, I guess you were stucked at the same point ? There is a bluez5 agent written in python in the source tree

**Comment by substring** [comment]
Well, i have to give up on Bluez5 for now for quite many reasons :

1. we rely on bluez 5.37, dual shock 3 clones patches are still not official after almost a year being submitted. Shanwans work, gasia don't, that's a no go
2. the bluez5 API is so much different than bluez4. Bluez4 could easily be driven through basic scripts whereas bluez5 need a dbus implementation. There are examples of how to write an agent, setup discovery etc ... too much work for a bt stack that doesn't work with GAsia
3. Things can't be done easily. Something like `echo "connect XX:XX:XX:XX:XX:XX | bluetoothctl` is not reliable at all. The only way around is using DBus
4. I found quite a nasty bug on my 8bitdo zero that worked fine with bluez4 `hidd` but not with bluez5 : all mouse related events simply vanished on bluez5

I may still have a trick up my sleeve, but i'll test that later

**Comment by DiRoiD** [comment]
Is the raspbian update helping with your problem?
https://www.raspberrypi.org/blog/another-update-raspbian/
They seems to had quite a lot of difficulties on this item also.

**Comment by substring** [comment]
@DiRoiD it just prooves me that using bluez5 is something complicated as they also had quite some trouble writing their own tool (a few weeks he said ...)
But anyway, i shall test raspbian to verify a bug i found. Who knows

**Comment by drcrimzon** [comment]
Hey @substring,
I agree that bluez5 is a PITA.  I have tried getting 5's hciattach with 4, but have not had luck with it working.
1. No way around gasia.
2. I have a dbus implementation working for somethings, but others it fails.  It is definitely not stable/reliable enough for a release.
3. Agreed
4. I think this is an easy fix, I'll try with my bluetooth mouse tonight.

It's a shame, since everything I want works (stock sixaxis) beautifully, and the nastyness that is bluez5 with lack of support of decent scripting or controller support is preventing anything outside of that from a realistic deployment.  i have looked at the other projects that have bluez5 and their pairing is all a nightmare 50% chance it might work.  (about the same as my experience with dbus scripts)

The only thing that would really work at this point is someone backporting the updated hciattach to bluez4.

**Comment by substring** [comment]
I've had a short look on hciattach of bluez4. The main .c has hardly changed, just need the bcm43xx function + the corresponding c file, maybe a header file. We'd also need to back port RPI bluez5 patches. No idea about the amount of work

But, I had hciattach of bluez5 work on top of bluez4. I think i may still have a built with it. I just compiled recalboxos, and fake an update from 4.0 (bluez4) to 4.1 (my build with blues5). It worked rather well, tbh. But It meant bluetoothd from bluez4, no sixaxis plugin ... Anyway that's a lead i may follow later. I'll keep you informed on this issue
Congratz for the dbus work ! you may be on the good way ! Even the RPI Foundation had a hard time with bluez5 (see their last blog update for raspbian)

**Comment by substring** [comment]
@fluffymadness here you'll get all infos you may want to know concerning Pi3 BT. For now, we're using bluez4 + sixad. Getting pi3 BT to work requires bumping to bluez5. I tested with @kivutar sixaxis on lakka as he's already using bluez5. Official pads work w/ bluez5, we found some patches for clones -> shanwans work, not gasias. The migration to blues5 is complicated, i've been working on it for some time, and there is still quite much work to do. I'll take a look at it again later

**Comment by fluffymadness** [comment]
Ah ok. Thx for the info :)

**Comment by substring** [comment]
reminder for myself : https://github.com/khvzak/bluez-tools

**Comment by fluffymadness** [comment]
@substring 
I guess you probably have this included already, but I still wanted to put it here, just in case :)
https://github.com/ValveSoftware/SteamOS/issues/479 (Dualshock3 bluez5 autopair)

**Comment by substring** [comment]
@fluffymadness thanks ! (but psssssst ... kivutar already told me about it ;) )

**Comment by fluffymadness** [comment]
thought so ^^

**Comment by paradadf** [comment]
This sound promising about bluez 5 and shanwan/gasia patches:
https://retropie.org.uk/forum/topic/42/shanwan-ps3-controller-pi3-retropie-3-6-bluetooth-setup/105

https://github.com/luetzel/bluez

**Comment by substring** [comment]
@paradadf yeah, that's a "hack" : using bluez5 to get pi3 bt support, but not using the bluez sixaxis plugin (which handles official, shanwans but not gasia), and still using QtSixA for PS3 pads management. Thought about it as long as PS3 clones are not yet fully handled byt bluez5. On the other hand, the real difficulty with bluez5 is to switch to dbus for scan / connect / pair

**Comment by jravetch** [comment]
@substring Thanks very much for your hard work.  What's the status of getting bluetooth to work on the PI3?

**Comment by substring** [comment]
Almost over, but gotta decide what to do with PS3 pads. Anyway it should ve in the 4.1 release, not the 4.0

**Comment by mcmasterp** [comment]
is 4.1 the next release or are you speaking of several releases away? I ask because just like everyone else I am finishing a bartop for my father and I'm trying to decide if I should get a bluetooth dongle or maybe just a wireless controller to eliminate the issue. But I already have a ps3 controller and pi3 so the cheap side of me wants to wait lol.

**Comment by substring** [comment]
@mcmasterp the cheap side of you will have to be very patient then, 4.1 should be released in a few months. That's the next major release after 4.0

**Comment by mcmasterp** [comment]
Haha good to know. I found an old Microsoft Bluetooth dongle which now seems to work as it lists my pcs in pair a Bluetooth device. Unfortunately I can't seem to get the ps3 controller to pair.

It seems like a wireless usb controller will be the easiest route for now. 

Cant wait for the update and all its goodies!

**Comment by travmason** [comment]
So I dumped retropie for recalbox but having all sorts of issues (as noticed here) getting the ps3 controller to work. Works fine in retropie - what's the different thing they're doing in their release compared to recalbox?

**Comment by kryptto** [comment]
I have had the same issues.  I have posted this fact many times. The truth is the new driver helped fix many issue and support more new controllers, etc...

Don't use the latest version and load the 3.3 version. https://github.com/recalbox/recalbox-os/releases/tag/v3.3.0-beta17

This is the only fix for difficult PS3 controller issues. There is a so called troubleshooting post someone has on these forums. It doesn't work for my PS3 controller that is having issues. I would try their 'fix' first then roll your version back to the version I am listing above.

Hopefully the dev team members will post in the next version that this issue has been fixed in the latest BT driver update.

Kryptto

via CloudMagic Email<https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.6.30&pv=6.0.1&source=email_footer_2>
On Sun, Jul 31, 2016 at 4:25 AM, Trav Mason <notifications@github.com<mailto:notifications@github.com>> wrote:


So I dumped retropie for recalbox but having all sorts of issues (as noticed here) getting the ps3 controller to work. Works fine in retropie - what's the different thing they're doing in their release compared to recalbox?

**Comment by travmason** [comment]
I went hacking last night and realised aid never used NOOBS before on the pi. No gcc? Not much of anything useful!
Does recallbox compile ok onto raspberian or other disto?

**Comment by substring** [comment]
@travmason The issue is about bt on pi3, not how the ps3 controllers behave in recalbox.

Recalbox is a full linux built from scratch, a whole os, when retropie is "just a set of scripts on top of an existing linux". Once again this is not the topic of that issue ;)

**Comment by travmason** [comment]
@substring I've been compiling, using, teaching and hacking the linux code since installing from floppy as 0.12 back at uni. I get what a raw install is and isn't. It just amazed me that these days with so many good distro's available, why there would be an attempt to "roll your own" and then wonder why things like basic drivers (bt) don't work consistently.
There's a reason we started things like slackware all those years ago - inconsistency in contribution to the various flavours that were being developed meant that we couldn't get everything to work all the time.
Now this release seems to be following the same dead end path so many others have made before.
I'm heading back to Retropie. Raspbian is a solid, reasonably light weight distro that updates regularly with a huge community of coders. I'd recommend the same.

**Comment by substring** [comment]
@travmason looks like you missed quite some things here :
- we are porting recalbox to other platforms. The Odroid XU4 port is almost done, C2 on its way. Pine64 and x86 are in the starting blocks (just look at the issues summary). How would you want us to achieve that if we rely on raspbian ?
- the choice was made not to rely on an existing "distro" for performance matters. Have you noticed that the same raspbian image works for both pi2 and pi3 whereas the pi3 architecture handles armv8, not just only armv7 ? On recalbox has seperate versions, compilation IS  optimized depending on the CPU architecture
- we are not fooling around with just "linux", recalbox is based on a well known system called buildroot which lets us write our own distro. I suggest you read a little about what buildroot is. Consider recalbox like an embedded system, then you'd realize why we don't use raspbian but rather buildroot.

Now, concerning BT, if you had read through the whole issue you would have understood that we don't support yet the pi3 bt because we have bluez4, whereas the pi3 bt needs a patched bluez5. As I'm the one porting bluez4 to bluez5 on recalbox i can tell you that I almost achieved that, but it raises some other problems concerning integration and official support for PS3 clones. The pi3 bt works just fine on my test system, maybe you'll reconsider your opinion once recalbox 4.1 is out ? I can't believe someone with your experience throws away recalbox for a simple bt problem, or just because you expect it to be a clone of raspbian + retropie. Have you at least tested recalbox ?

Recalbox is made for being a "gaming" box, not an everyday OS with emulators running on top of it :)

Shall we stop this non sense trolling now ?

**Comment by nadenislamarre** [comment]
@travmason you can consider buildroot as the distribution on which recalbox is based (even it's not technically a distribution). 99% of the recalbox is done by the buildroot team and other projects.
Personnally, i don't consider raspbian as a good choice for embeded system, but more for desktop system.

A simple example among several others : the recalbox filesystem is read only, which is not the case on the raspbian. It's just a prerequisite if you want a robust system on an sd card which doesn't like outages.

I like the very good argument of substring : we have only 1 source for several plateform (this is the aim of buildroot) : rpi0, rpi1, rpi2, rpi3, odroid xu3, odroid xu4 and the coming x86, x86_64, odroid c2, pine64. No need to reinvent the wheel for each embeded system : all what is true for desktop os is not true for embeded os.

**Comment by travmason** [comment]
@substring @nadenislamarre Good responses, good points.
I hadn't read far enough back on the issue to understand the current version was bluez4.
Understand buildroot is the base now ;-)
How can I help?

**Comment by substring** [comment]
@travmason it's almost done. There's a branch on my repo where i moved to bluez5, but didn't make any pr yet. 2 things are left : make gasia pads work, and widely test it. Might be a small trick for pad reconnection too, the very few people with who i shared a working image had some issues with some pads not reconnecting after going to sleep

**Comment by travmason** [comment]
The only gasia pad I have is in bits so can't help test there. I had the reconnect issue on Retropie too so based on a sample of one it's common. Got a link to that repo? I'll compile and test on my kit.

**Comment by nadenislamarre** [comment]
@travmason i've initialized a wiki in case you want to work on recalbox :
https://github.com/recalbox/recalbox-os/wiki/Recalbox-development---basics-%28EN%29

@substring don't hesitate to add information in it ;-)

**Comment by nadenislamarre** [comment]
@travmason https://github.com/substring/recalbox-buildroot/tree/rb-4.1.X-bluez5

**Comment by substring** [comment]
@travmason check my profile, recalbox-buoldroot repo, carefully look at the branches ;)

**Comment by travmason** [comment]
Cheers. Branch complexity always lends me to ask for the direct link ;-)

--
Travis Mason
travis.mason@gmail.com

**Comment by dudo** [comment]
@substring I love hearing you have BT running on the Pi3. If you have it working for a handful of devices, I'd say embrace the Pareto principle and release it for the masses. I really wanna play wirelessly!

**Comment by travmason** [comment]
Hit this compiling the 4-1-bluez5 branch.
Something old referenced?
http://pastebin.com/nQHiSW1u

--
Travis Mason
travis.mason@gmail.com

**Comment by substring** [comment]
@dudo it's not merged yet in the recalbox main branches because there some things i have to discuss with @digitalLumberjack 
@travmason looks like since retroarch 1.3.6, they deleted the imageviewer repo ... gonna check this out. Meanwhile, disable the package and keep compiling

**Comment by nadenislamarre** [comment]
to disable :
edit configs/recalbox_yours_defconfig and remove libretro_imageviewer then,
make recalbox-yours and make
or edit the .confg to replace =y by not set on the correct like then make.

**Comment by substring** [comment]
easier with the .config ;)

**Comment by fenomeno0chris** [comment]
Hi, Im using the latest version of recalbox (4.0.0 - Build 121). It was very easy to set everything up on my rPi3. Thank you very much for this great operating system!

There are just a few questions I still have.
- Is there a way to use the DualShock4 wirelessly with the built-in bluetooth feature of the rPi3?
- Where do I find different themes for recalbox? (In the UI-Settings is an option to change the theme, but there is just one to choose from.)
- What is the pixel-perfect setting good for?
- How can I overclock the RaspberryPi? It can not be changed in the settings. 
- Is it possible to change the background music? If yes, where can I find other background songs?

Keep up the great work you guys are doing!

**Comment by rockaddicted** [comment]
@fenomeno0chris everything is support request, not system issue -> go open a thread https://forum.recalbox.com/ :wink:

**Comment by substring** [comment]
After countless hours, dozens of img burnt to some SD cards ... at last it came out with great pain ^^

**Comment by nadenislamarre** [comment]
congratulation !!!
and what the title doesnt say is that it will help than just the rpi3.

**Comment by mcmasterp** [comment]
Way to go and thank you very much

**Comment by LehMarc** [comment]
Hello, my name is Marc and I'm new here;) I use since yesterday the latest version of recalboxOS 4.0.0 with 8bitdo SFC30 controller on a PI3. In addition, I have bought a bluetooth dongle.

I have now read the whole thread, I can not figure it out.

Is there now a possibility, or a workaround to enable the Controller under recalboxos 4.0.0? Or it will work only in 4.1?

Excuse my bad english, it's not my native language.

**Comment by substring** [comment]
Hey marc
This is not the place to ask for support. Please join the forum and start a topic :)

**Comment by danielo515** [comment]
May I ask what is the status of this issue? I can wait until 4.1 but I just want to know how much 😄
